services:
  service-sparkit:
    image: sparkit-service
    container_name: sparkit-service
    depends_on:
      sparkit-postgres:
        condition: service_healthy
    environment:
      PSQL_HOST: "sparkit-postgres:5432"
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_DBNAME: "sparkitDB"
    ports:
      - '8080:8080'
    volumes:
      - ~/imagedata:/home/${OS_USER}/imagedata

  service-sparkit-auth:
    image: sparkit-auth-service
    container_name: sparkit-auth-service
    depends_on:
      sparkit-redis:
        condition: service_healthy
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - '8081:8081'

  service-sparkit-personalities:
    image: sparkit-personalities-service
    container_name: sparkit-personalities-service
    depends_on:
      sparkit-postgres:
        condition: service_healthy
    environment:
      PSQL_HOST: "sparkit-postgres:5432"
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_DBNAME: "sparkitDB"
    ports:
      - '8083:8083'

  service-sparkit-communications:
    image: sparkit-communications-service
    container_name: sparkit-communications-service
    depends_on:
      sparkit-postgres:
        condition: service_healthy
    environment:
      PSQL_HOST: "sparkit-postgres:5432"
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_DBNAME: "sparkitDB"
    ports:
      - '8082:8082'

  service-sparkit-message:
    image: sparkit-message-service
    container_name: sparkit-message-service
    depends_on:
      sparkit-postgres:
        condition: service_healthy
    environment:
      PSQL_HOST: "sparkit-postgres:5432"
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_DBNAME: "sparkitDB"
    ports:
      - '8084:8084'
  service-sparkit-survey:
    image: sparkit-survey-service
    container_name: sparkit-survey-service
    depends_on:
      sparkit-postgres:
        condition: service_healthy
    environment:
      PSQL_HOST: "sparkit-postgres:5432"
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_DBNAME: "sparkitDB"
    ports:
      - '8085:8085'

  sparkit-postgres:
    image: postgres:latest
    container_name: sparkit-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "sparkitDB"
    healthcheck:
      test: [
        "CMD", "pg_isready",
        "--dbname", "sparkitDB",
        "--host", "sparkit-postgres",
        "--port", "5432",
        "--username", "reufee"
      ]
      timeout: 2s
      retries: 2
      start_period: "3s"
    ports:
     - "5432:5432"
    volumes:
      - ../build/sql/create_tables.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ~/postgresdata:/var/lib/postgresql/data

  sparkit-redis:
    image: redis:latest
    container_name: sparkit-redis
    environment:
      - REDIS_PASSWORD=$(REDIS_PASSWORD)
      - REDIS_USER=$(REDIS_USER)
      - REDIS_USER_PASSWORD=$(REDIS_USER_PASSWORD)
    ports:
      - "6379:6379"
    volumes:
    -  ~/redisdata:/data

    command: >
      sh -c '
              mkdir -p /usr/local/etc/redis &&
              echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
              echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
              echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
              echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
              echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
              echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
              redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
            '
      
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true





