global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: "main"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-service:8080' ]

  - job_name: "auth"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-auth-service:8031' ]

  - job_name: "communications"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-communications-service:8032' ]

  - job_name: "personalities"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-personalities-service:8033' ]

  - job_name: "message"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-message-service:8034' ]

  - job_name: "survey"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'sparkit-survey-service:8035' ]
